print("Welcome to the Band Name Generater")
city = input("Which city did you grow up in? ")
print(city) 
pet = input("What is the name of your pet? ")
print("Your band name could be:" + city + " " + pet)
